development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_test
  pool: 5
  username: root
  password: supersecretpassword
  socket: /var/run/mysqld/mysqld.sock
  host: 127.0.0.1

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_production
  pool: 5
  username: root
  password: supersecretpassword
  socket: /var/lib/mysql/mysql.sock
  host: 127.0.0.1